Limit compile time.
vijos/jd4 pull request #2
Opened 2017-03-12 08:04 UTC by twd2

2017-03-12 21:00 UTC, iceboy233 requested changes

2017-03-12 21:00 UTC, iceb0y commented on .travis.yml
> +  - CXX=g++-4.8 TRAVIS_NODE_VERSION="6.9.4"
???

2017-03-12 21:00 UTC, iceb0y commented on .travis.yml
> +  - apt install libseccomp-dev linux-libc-dev
???

2017-03-12 21:00 UTC, iceb0y commented on jd4/case.py
> +        super().__init__(DEFAULT_TIME_MS * 1e6, DEFAULT_MEM_KB * 1024, PROCESS_LIMIT, 10)
1e6 is float. You should write 1000000.

2017-03-12 21:00 UTC, iceb0y commented on jd4/daemon.py
> +                self.type = self.request.pop('type')
move this into `__init__`.

also note that the `problem_data_change` event should not be handled by `JudgeHandler`.

2017-03-12 21:00 UTC, iceb0y commented on jd4/daemon.py
> +            if self.type == 1:
could you write like this:

```
case = {...}
if self.type == 1:
    case['judge_text'] = ...
```

2017-03-12 21:00 UTC, iceb0y commented on jd4/cgroup.py
> +PROCESS_LIMIT = 32
These default limits should not be put here and imported.

2017-03-12 21:00 UTC, iceb0y commented on jd4/langs.py
> +                time_limit_ns=lang_config.get('time_limit_ms', DEFAULT_TIME_MS) * 1e6,
1e6 is float.

2017-03-12 21:00 UTC, iceb0y commented on jd4/case.py
> +                       PROCESS_LIMIT, DEFAULT_TIME_MS, DEFAULT_MEM_KB
These constants should be put in file rather than imported.

2017-03-12 21:00 UTC, iceb0y commented on examples/langs.yaml
> +    time_limit_ms: 20000
Let's use default value and not adding it here.

2017-03-17 14:40 UTC, twd2 commented
@iceb0y

2017-03-17 18:30 UTC, iceb0y commented on jd4/daemon.py
> +        self.event = self.request.pop('event', None)
Move this event handling out of judge handler. i.e. you can add an EventHandler, though the naming is weird.

2017-03-17 18:34 UTC, iceb0y commented on jd4/daemon.py
> +                case['judge_text'] = ''
I thought judge_text was optional.
Since it's mandatory, let's revert this ^_^T_T

2017-03-18 04:43 UTC, iceb0y commented on jd4/pool.py
> +                time_limit_ns=lang_config.get('time_limit_ms', DEFAULT_TIME_MS) * 1000000,
please put these into _compiler_build()

2017-03-19 13:20 UTC, merged